BLOBUTYPE.DEBUG_NULL_SAFE_GET=BlobUserType.nullSafeGet
BLOBUTYPE.DEBUG_NULL_SAFE_SET=BlobUserType.nullSafeSet
BLOBUTYPE.ERROR_0001_SETTING_BLOB=definindo blob

CONTFILE.ERROR_0001_FILE_CANNOT_BE_READ=o arquivo {0} n\u00e3o pode ser lido.
CONTFILE.ERROR_0002_FILE_DOES_NOT_EXIST=o arquivo {0} n\u00e3o existe.
CONTFILE.ERROR_0003_OVERWRITE_DISALLOWED=o arquivo {0} n\u00e3o pode ser sobrescrito.
CONTFILE.ERROR_0004_CANNOT_DELETE_FOR_CREATE=o arquivo {0} n\u00e3o pode ser deletado ou criado
CONTFILE.ERROR_0005_CANNOT_CREATE=o arquivo {0} n\u00e3o pode ser criado
CONTFILE.ERROR_0006_DURING_COPY=durante c\u00f3pia do arquivo {0} para o arquivo {1}.
CONTITEM.ERROR_0001_NO_EXISTING_FILES=N\u00e3o h\u00e1 entrada dispon\u00edvel porque este item de conte\u00fado ({0}) n\u00e3o teve nada escrito.
CONTITEM.ERROR_0002_NO_EXISTING_FILES=N\u00e3o h\u00e1 entrada dispon\u00edvel porque este item de conte\u00fado ({0}) n\u00e3o teve nada escrito.
CONTITEM.ERROR_0003_BAD_WRITE_MODE=Falha no modo escrita {0}.
CONTITEM.ERROR_0004_OUTPUT_STREAM_NOT_AVAILABLE=OutputStream n\u00e3o dispon\u00edve\u00e7
CONTITEM.ERROR_0005_COULD_NOT_DELETE_OS_FILE=Falha ao deletar arquivo OS {0}.
CONTITEM.ERROR_0006_ACTION_NAME_CANNOT_BE_NULL=Nome da a\u00e7\u00e3o n\u00e3o pode ser nula.

CONTLOC.ERROR_0002_CANNOT_CREATE_TMPFILE=Falha ao criar arquivo tempor\u00e1rio no diret\u00f3rio {0}.
CONTLOC.ERROR_0003_MKDIR=Falha ao criar subdiret\u00f3rio {0}.
CONTLOC.ERROR_0004_PATH_DOES_NOT_EXIST=O caminho especificado ({0}) n\u00e3o existe.

CONTREP.DEBUG_CREATE_LOCATION_ID=Id de localiza\u00e7\u00e3o criado {0}
CONTREP.DEBUG_NEW_LOCATION=Criando nova localiza\u00e7\u00e3o para {0}
CONTREP.ERROR_0004_SAVING_LOCATION=Erro ao salvar localiza\u00e7\u00e3o do conte\u00fado.
CONTREP.ERROR_0002_GETTING_LOCATION=Erro ao obter localiza\u00e7\u00e3o - {0}
CONTREP.ERROR_0003_GETTING_CONTENT_BY_ID=Erro ao obter conte\u00fado por id - {0}
CONTREP.ERROR_0005_SAVING_BACKGROUND_CONTENT_ID=Erro ao salvar id de conte\u00fado de background - {0}

ContentItem.ERROR_0001_CLOSE_OUTPUT_STREAM=Falha ao fechar stream de sa\u00edda

EMPTYSTRTYPE.CODE_PENTAHO_EMPTY_STRING=_PENTAHOEMPTY_
EMPTYSTRTYPE.DEBUG_NULL_SAFE_GET=EmptyStringUserType.nullSafeGet()
EMPTYSTRTYPE.DEBUG_NULL_SAFE_SET=EmptyStringUserType.nullSafeSet()

FileInfo.ERROR_0001_DOCUMENT_HAS_NO_TYPE=Documento da solu\u00e7\u00e3o n\u00e3o tem tipo
FileInfo.ERROR_0002_COULD_NOT_LOAD=Falha ao carregar documento da solu\u00e7\u00e3o

HIBFILTER.INFO_INIT=Pentaho Hibernate Filter Init - Agora abrindo e fechando sess\u00e3o para cada requisi\u00e7\u00e3o
HIBUTIL.DEBUG_CLOSING_SESSION=Fechando a Sess\u00e3o para esta thread.
HIBUTIL.DEBUG_COMMIT_TRANS=Realizando commit para transa\u00e7\u00e3o de banco de dados desta thread.
HIBUTIL.DEBUG_MAKE_PERSISTENT=Fazendo objeto persistente - {0}
HIBUTIL.DEBUG_MAKE_TRANSIENT=Tornando o objeto transiente (deletando do Hibernate) - {0}
HIBUTIL.DEBUG_OPEN_NEW_SESSION=Abrindo nova Sess\u00e3o para esta thread.
HIBUTIL.DEBUG_ROLLBACK=Tentando realizar rollback de transa\u00e7\u00e3o no banco de dados dessa thread.
HIBUTIL.DEBUG_START_TRANS=Iniciando nova transa\u00e7\u00e3o de banco de dados nesta thread.
HIBUTIL.DEBUG_USING_INTERCEPTOR=Usando interceptor:
HIBUTIL.ERROR_0002_DISCONNECT=disconnectSession() falhou.
HIBUTIL.ERROR_0003_ROLLBACK=rollbackTransaction() falhou.
HIBUTIL.ERROR_0004_START_TRANS=beginTransaction() falhou.
HIBUTIL.ERROR_0005_GET_SESSION=getSession() falhou.
HIBUTIL.ERROR_0006_BUILD_SESSION_FACTORY=Falha na construi\u00e7\u00e3o do SessionFactory.
HIBUTIL.ERROR_0007_REBUILD_SESSION_FACTORY=rebuildingSessionFactory falhou.
HIBUTIL.ERROR_0008_COMMIT_TRANS=commitTransaction() falhou.
HIBUTIL.ERROR_0009_CLOSE_SESSION=closeSession() falhou.
HIBUTIL.ERROR_0010_SAVING_UPDATING=salvando ou atualizando objeto Hibernate.
HIBUTIL.ERROR_0011_DELETING_OBJ=deletando objeto do Hibernate.
HIBUTIL.ERROR_0012_CONFIG_NOT_FOUND=Arquivo de configura\u00e7\u00e3o especificado no contexto da aplica\u00e7\u00e3o ({0}) n\u00e3o pode ser encontrado.
HIBUTIL.ERROR_0013_NO_SESSION_FACTORY=Configura\u00e7\u00e3o gerenciada especificada, mas hibernate.session_factory_name n\u00e3o est\u00e1 especificada no arquivo de configura\u00e7\u00e3o.
HIBUTIL.ERROR_0014_EVICTING_OBJECT=Falha ao retirar objeto do cache do Hibernate.
HIBUTIL.ERROR_0420_CONFIGURATION_ERROR_NO_HIB_CFG_FILE_SETTING=Erro de Configura\u00e7\u00e3o - n\u00e3o encontrou defini\u00e7\u00e3o do arquivo de configura\u00e7\u00e3o do Hibernate - tentando pard\u00e3o hibernate.cfg.xml.
HIBUTIL.USER_HIBERNATEMANAGED=Hibernate sendo usado em ambiente gerenciado - usando JNDI para factory.
HIBUTIL.USER_HIBERNATEUNMANAGED=Hibernate sendo usando em ambiente n\u00e3o gerenciado - usando static para factory.

LONGSTRTYPE.DEBUG_NULL_SAFE_GET=LongStringUserType.nullSafeGet()
LONGSTRTYPE.DEBUG_NULL_SAFE_SET=LongStringUserType.nullSafeSet()

RTELEMENT.ERROR_0001_INVALIDUPDATE=Atualiza\u00e7\u00e3o de elemento de runtime \u00e9 inv\u00e1lida - atualmente apenas leitura.

RTREPO.DEBUG_CREATE_INSTANCE=instanceId criado: {0}
RTREPO.DEBUG_LOAD_ELEMENT_BY_ID=loadElementById({0})
RTREPO.DEBUG_NEW_ELEMENT_PARENT=newRuntimeElement({0},{1})
RTREPO.DEBUG_NEW_ELEMENT_PARENT_SOLN=newRuntimeElement({0},{1},{2})
RTREPO.DEBUG_PROPERTY_GETSET=RuntimeElement.{0}Property - {1}
RTREPO.ERROR_0001_INVALIDTYPE=Tipo de par\u00e2metro n\u00e3o correponde - par\u00e2metro era {0}, est\u00e1 sendo definido para {1}
RTREPO.ERROR_0001_LOAD_ELEMENT=Erro ao carregar elemento {0}
RTREPO.ERROR_0002_SAVING_ELEMENT=Erro ao salvar elemento para sess\u00e3o
RTREPO.ERROR_0003_SAVING_ELEMENT=Erro ao salvar elemento para sess\u00e3o

RuntimeContext.ERROR_0024_NO_CONTENT_REPOSITORY=Falha ao obter reposit\u00f3rio de conte\u00fado
RuntimeContext.ERROR_0025_INVALID_CONTENT_LOCATION=Falha ao obter localiza\u00e7\u00e3o do conte\u00fado
SOLREPO.ERROR_0006_MISSING_RESOURCE=Recurso n\u00e3o encontrado: {0}

SOLREPO.AUDIT_DEL_FILE=Arquivo Deletado: {0}
SOLREPO.AUDIT_DEL_FOLDER=Pasta Deletada: {0}

CleanRepoPublisher.CLEAN_REPO=Limpar Reposit\u00f3rio
CleanRepoPublisher.CLEAN_REPO_DESCRIPTION=Remove arquivos do reposit\u00f3rio de conte\u00fado que possuem mais do que 180 dias.
CleanRepoPublisher.CLEAN_REPO_DONE=O reposit\u00f3rio foi limpo
CleanRepoPublisher.ERROR_0001_CLEAN_REPO_FAILED=O limpador de reposit\u00f3rio encontrou erros: {0}

SolutionRepository.DEBUG_ADDING_ACTION=Adicionando a\u00e7\u00e3o ao reposit\u00f3rio da solu\u00e7\u00e3o {0}
SolutionRepository.DEBUG_FILE_LIST_XPATH=getFileList xPath={0}
SolutionRepository.DEBUG_FILE_PATH=getFile path={0}
SolutionRepository.ERROR_0001_FILE_DOES_NOT_EXIST=Arquivo n\u00e3o existe {0}
SolutionRepository.ERROR_0002_NULL_RUNTIME_CONTEXT=Contexto de Tempo de Execu\u00e7\u00e3o \u00e9 nulo
SolutionRepository.ERROR_0003_NULL_SOLUTION_FILE=Arquivo n\u00e3o existe na solu\u00e7\u00e3o {0}
SolutionRepository.ERROR_0004_INVALID_CONTEXT=getActionDefinition - contexto, id da inst\u00e2ncia e nome da a\u00e7\u00e3o n\u00e3o s\u00e3o todos v\u00e1lidos
SolutionRepository.ERROR_0005_INVALID_SOLUTION_FILE=Falha ao encontrar documento Action Definition
SolutionRepository.ERROR_0006_INVALID_SEQUENCE_DOCUMENT=Documento de sequencia de a\u00e7\u00e3o de solu\u00e7\u00e3o n\u00e3o \u00e9 v\u00e1lido {0}
SolutionRepository.ERROR_0007_COULD_NOT_READ_PROPERTIES=Falha ao ler arquivo properties {0}
SolutionRepository.ERROR_0008_ACTION_SEQUENCE_NAME_INVALID=Nenhum nome ou caminho especificado para a sequencia de a\u00e7\u00e3o
SolutionRepository.ERROR_0009_INVALID_DOCUMENT=O documento da solu\u00e7\u00e3o {0} n\u00e3o \u00e9 um documento XML v\u00e1lido XML
SolutionRepository.ERROR_0012_INVALID_SOLUTION_ROOT=Pasta raiz da solu\u00e7\u00e3o ({0}) \u00e9 inv\u00e1lida.
SolutionRepository.ERROR_0013_RESET_FAILED=Falha de Reset: {0}
SolutionRepository.ERROR_0014_COULD_NOT_SAVE_FILE=Falha ao salvar arquivo: {0}
SolutionRepository.ERROR_0015_SET_PERMISSIONS_DENIED=Pedido para definir permiss\u00f5es no arquivo "{0}" negado.
SolutionRepository.ERROR_0016_FAILED_TO_CREATE_ACTION_SEQUENCE=Falha ao criar sequencia de a\u00e7\u00e3o {0}
SolutionRepository.ERROR_0017_INVALID_XML_DOCUMENT=O documento xml \u00e9 inv\u00e1lido {0}
SolutionRepository.ERROR_0019_NO_DATA_IN_FILE=O arquivo n\u00e3o tem nenhum dado {0}
SolutionRepository.ERROR_0020_FILE_IS_NOT_READABLE=N\u00e3o \u00e9 poss\u00edvel ler o arquivo {0}
SolutionRepository.ERROR_0021_FILE_NOT_ADDED=Falha ao adicionar ao reposit\u00f3rio {0}
SolutionRepository.ERROR_0022_HIBERNATE_EXCEPTION=Hibernate n\u00e3o pode retornar resultados para o arquivo {0}
SolutionRepository.ERROR_0023_INVALID_PUBLISH_LOCATION_ROOT=Local de publica\u00e7\u00e3o inv\u00e1lido: Pasta Raiz
SolutionRepository.ERROR_0024_CREATING_CLASSLOADER=Falha ao criar Class Loader
SolutionRepository.USER_DELETE_FOLDER_WARNING=Dele\u00e7\u00e3o de pasta chamada com uma refer\u00eancia de arquivo... deveria ser uma refer\u00eancia de pasta
SolutionRepository.WARN_MISSING_RESOURCE_PROPERTY=Propriedade "{0}" faltando em um arquivo de recurso "{1}" para "{2}"
SolutionRepository.WARN_0001_UNDEFINED_SOLUTION_NAME=Nome do Reposit\u00f3rio da Solu\u00e7\u00e3o n\u00e3o definido no n\u00f3 solution-repository/db-repository-name de Pentaho.xml
SolutionRepository.WARN_0002_USING_SOLUTION_NAME=Usando nome da solu\u00e7\u00e3o: {0}
SolutionRepository.WARN_0003_REPOSITORY_NOT_FOUND_BY_NAME=Falha ao encontrar reposit\u00f3rio pelo nome {0}

SolutionRepository.ACCESS_DENIED=Acesso a {0} para opera\u00e7\u00e3o {1} foi negado.
SolutionRepository.INFO_0001_BEGIN_LOAD_DB_REPOSITORY=BEGIN - UPDATE SOLUTION FROM FILE SYSTEM
SolutionRepository.INFO_0002_UPDATED_FOLDER=UPDATED - FOLDER: {0}
SolutionRepository.INFO_0003_END_LOAD_DB_REPOSITORY=END - UPDATE SOLUTION FROM FILE SYSTEM
SolutionRepository.INFO_0004_ADDED_FOLDER=ADDED - FOLDER: {0}
SolutionRepository.INFO_0006_ADDED_FILE=ADDED - FILE: {0}
SolutionRepository.INFO_0007_UPDATED_FILE=UPDATED - FILE: {0}
SolutionRepository.INFO_0008_NOT_ADDED=Arquivo da Solu\u00e7\u00e3o: "{0}" N\u00e3o adicionado.  Assume-se que esteja na pasta admin.
SolutionRepository.INFO_0009_RESET_SUCCESS=Reset bem sucedido.  ACLS padr\u00e3o aplicado.
SolutionRepository.INFO_0010_DOCUMENT_NOT_FOUND=Falha ao encontrar documento {0}
#Query Stuff
SolutionRepository.QUERY_COLUMN_NAME=filename
SolutionRepository.QUERY_COLUMN_PARENT=parent
SolutionRepository.QUERY_COLUMN_PATH=fullPath

SubscriptionHelper.USER_SUBSCRIPTION_NOT_CREATE=O agendamento p\u00fablico n\u00e3o pode ser criado
SubscriptionHelper.USER_SUBSCRIPTION_CREATED=Agendamento P\u00fablico salvo/criado
SubscriptionHelper.ACTION_SEQUENCE_NOT_ALLOWED=Sequencia de A\u00e7\u00e3o n\u00e3o permitida para agemdamento p\u00fablico: {0}
SubscriptionHelper.USER_SUBSCRIPTION_NOT_DELETED=Falha ao deletar Agendamento P\u00fablico
SubscriptionHelper.USER_SUBSCRIPTION_DELETED=Agendamento P\u00fablico deletado
SubscriptionHelper.USER_ARCHIVE_NOT_FOUND=relat\u00f3rio arquivado n\u00e3o pode ser encontrado
SubscriptionHelper.USER_SUBSCRIPTION_DOES_NOT_EXIST=O agendamento p\u00fablico n\u00e3o existe
SubscriptionHelper.USER_CONTENT_ITEM_DOES_NOT_EXIST=O item de conte\u00fado n\u00e3o existe
SubscriptionHelper.USER_ARCHIVE_DELETED=O item arquivado foi deletado
SubscriptionHelper.USER_LOGIN_NEEDED=Voc\u00ea deve logar antes de salvar
SubscriptionHelper.USER_SUBSCRIPTION_NAME_ALREADY_EXISTS=O agendamento p\u00fablico de nome "{0}" j\u00e1 existe.  Por favor mude o nome ao editar.

SubscriptionPublisher.ERROR_0001=N\u00e3o foi poss\u00edvel encontrar arquivo: {0}
SubscriptionPublisher.ERROR_0002=N\u00e3o foi poss\u00edvel encontrar arquivo: {0}
SubscriptionPublisher.ERROR_0003=N\u00e3o foi poss\u00edvel converter documento xml: {0}
SubscriptionPublisher.ERROR_0004=N\u00e3o foi poss\u00edvel converter documento xml: {0}
SubscriptionPublisher.ERROR_0005=Exce\u00e7\u00e3o de IO Desconhecida para arquivo: {0}
SubscriptionPublisher.ERROR_0006=Exce\u00e7\u00e3o de IO Desconhecida para arquivo: {0}
SubscriptionPublisher.ERROR_0007=Um erro nao-espec\u00edfico ocorreu.  Resultados s\u00e3o imprevis\u00edveis.  Verificar log.
SubscriptionPublisher.INFO_0001=Agendamentos e Conte\u00fado Publicados Com Sucesso
SubscriptionPublisher.INFO_0002=Publica agendamentos e conte\u00fado importados
SubscriptionPublisher.INFO_0003=Publicador de Assinatura

SubscriptionExecute.DEBUG_EXECUTION_INFO=Execu\u00e7\u00e3o {0} agendada
SubscriptionExecute.DEBUG_FINISHED_EXECUTION=Execu\u00e7\u00e3o de {0} finalizada
SubscriptionExecute.ERROR_0001_SOLUTION_NAME_MISSING=Nome da solu\u00e7\u00e3o n\u00e3o fornecido
SubscriptionExecute.ERROR_0001_UNABLE_TO_GET_SCHEDULE=Falha ao obter agendamento para: {0}
SubscriptionExecute.ERROR_0002_ACTION_PATH_MISSING=Caminho da a\u00e7\u00e3o n\u00e3o fornecido
SubscriptionExecute.ERROR_0003_ACTION_NAME_MISSING=Nome da a\u00e7\u00e3o n\u00e3o fornecido
SubscriptionExecute.ERROR_0004_SCHEDULE_DELETE_FAILED=Falha ao deletar agendamento p\u00fablico "{0}" do Reposit\u00f3rio de Assinatura durante a execu\u00e7\u00e3o final do agendamento.
SubscriptionExecute.ERROR_0005_INVALID_CRON_OR_REPEAT=Agendamento p\u00fablico com id "{0}" n\u00e3o possui nem uma string Cron nem um intervalo/conta repetida especificada.
SubscriptionExecute.INFO_TRIGGER_TIME=Provocado {0} em: {1} : {2}
SubscriptionExecute.EMAIL_BODY_MESSAGE=Esta mensagem foi automaticamente gerada por uma assinatura  do Pentaho BI server.

PRO_SUBSCRIPTREP.ERROR_0001_GETTING_SUBSCRIPTION=Falha ao obter agendamento p\u00fablico {0}
PRO_SUBSCRIPTREP.ERROR_0002_GETTING_SCHEDULE=Falha ao obter agendamento {0}
PRO_SUBSCRIPTREP.ERROR_PROCESSING_IMPORTS=Uma exce\u00e7\u00e3o ocorreu enquanto processava imports:
PRO_SUBSCRIPTREP.EXCEPTION_WITH_SCHEDULE=Um erro ocorreu com agendamento {0}
PRO_SUBSCRIPTREP.SCHEDULE_REF_NOT_UNIQUE_ADD=Falha ao adicionar Agendamento com nome {0}. Nomes de agendamentos devem ser \u00fanicos.
PRO_SUBSCRIPTREP.ADDED_SUBSCRIPTION_SCHEDULE=Adicionado Agendamento de Assinatura {0}
PRO_SUBSCRIPTREP.ADDED_SUBSCRIPTION_CONTENT=Adicionado Conte\u00fado de Assinatura {0}
PRO_SUBSCRIPTREP.USER_IMPORT_PROCESSING_SCHEDULES=Processsando {0} n\u00f3s de agendamentos.
PRO_SUBSCRIPTREP.NO_SCHEDULES_DEFINED=N\u00e3o h\u00e1 agendamentos definidos no documento importado.
PRO_SUBSCRIPTREP.CANNOT_EDIT_SCHEDULE=Falha ao editar Agendamento com id={0}
PRO_SUBSCRIPTREP.CANNOT_EDIT_CONTENT=Falha ao editar Conte\u00fado com id={0}
PRO_SUBSCRIPTREP.ERROR_OCCURRED_WITH_SCHEDULE=Um erro ocorreu com agendamento {0} : {1}
PRO_SUBSCRIPTREP.ERROR_WITH_CONTENT_LOG=Um erro ocorreu com conte\u00fado {0}
PRO_SUBSCRIPTREP.SCHEDULE_ID_NOT_FOUND=Id do agendamento {0} n\u00e3o foi encontrado
PRO_SUBSCRIPTREP.SUBSCRIPTION_ID_NOT_FOUND=Id de assinatura {0} n\u00e3o foi encontrado
PRO_SUBSCRIPTREP.USER_PROCESSING_CONTENT_NODES=Processando {0} n\u00f3s de conte\u00fado.
PRO_SUBSCRIPTREP.ACTION_SEQUENCE_ALREADY_EXISTS=Falha ao adicionar conte\u00fado de Assinatura para a\u00e7\u00e3o: {0}. Sequencia de A\u00e7\u00e3o j\u00e1 existe
PRO_SUBSCRIPTREP.MODIFIED_SUBSCRIPTION_SCHEDULE=Agendamento P\u00fablico Modificado {0}
PRO_SUBSCRIPTREP.MODIFIED_SUBSCRIPTION_CONTENT=Conte\u00fado de Assinatura Modificada {0}
PRO_SUBSCRIPTREP.SCHEDULE_REF_NOT_UNIQUE_EDIT=Falha ao editar Agendamento com refer\u00eancia {0}. Refer\u00eancia de agendamento deve ser \u00fanico
PRO_SUBSCRIPTREP.EXCEPTION_PROCESSING_IMPORTS=Uma exce\u00e7\u00e3o ocorreu enquanto processando imports
PRO_SUBSCRIPTREP.USER_REMOVING_USER=Removendo assinaturas e conte\u00fado de usu\u00e1ro para: {0}
PRO_SUBSCRIPTREP.DOCUMENT_IS_NULL=O documento importado \u00e9 nulo.
PRO_SUBSCRIPTREP.ERROR_WITH_CONTENT=Um erro ocorreu com conte\u00fado {0} : {1}

DbRepositoryClassLoader.RESOURCE_NOT_FOUND=N\u00e3o pode encontrar recurso [{0}] - NOTA: esta pode ser aceit\u00e1vel

MondrianCatalogPublisher.ERROR_0005_PUBLISH_EXCEPTION=Exce\u00e7\u00e3o ocorreu enquando publicava

DatasourceMgmtService.ERROR_0001_UNABLE_TO_CREATE_DATASOURCE=Erro ocorreu enquanto salvava o datasource {0}. Causa: {1}
DatasourceMgmtService.ERROR_0002_UNABLE_TO_DELETE_DATASOURCE=Erro ocorreu ao deletar o datasource {0}. Causa: {1}
DatasourceMgmtService.ERROR_0003_UNABLE_TO_UPDATE_DATASOURCE=Erro ocorreu ao atualizar o datasource {0}. Causa: {1}
DatasourceMgmtService.ERROR_0004_UNABLE_TO_RETRIEVE_DATASOURCE=Erro ocorreu ao recuperar o datasource {0}. Causa: {1}
DatasourceMgmtService.ERROR_0005_DATASOURCE_ALREADY_EXIST=Datasource {0} j\u00e1 existe na database, n\u00e3o pode adicionar a datasource com nome igual
DatasourceMgmtService.ERROR_0006_DATASOURCE_DOES_NOT_EXIST=Falha ao recuperar o datasource do datasource j\u00e1 que o nome do datasource {0} n\u00e3o existe
DatasourceMgmtService.ERROR_0007_UNABLE_TO_ENCRYPT_PASSWORD=Falha ao criptografar senha
DatasourceMgmtService.ERROR_0008_UNABLE_TO_DECRYPT_PASSWORD=Falha ao criptografar senha
DatasourceMgmtService.ERROR_0009_UNABLE_TO_INIT_PASSWORD_SERVICE=Falha ao instanciar IPasswordService
DatasourceMgmtService.ERROR_0010_NULL_DATASOURCE_OBJECT="Objeto Datasource recebido \u00e9 nulo
UserSettingService.ERROR_0001_INSUFFICIENT_PRIVILEGES=Privil\u00e9gios insuficientes para definir configura\u00e7\u00e3o de usu\u00e1rio global.
ERROR.Restoring_Password=Could restore password for user {0}. Setting a temporary password.
ERROR.CreatingUser=Could not create user {0}.
ROLE.Already.Exists=Role {0} already exists, could not create it.
USER.Already.Exists=User {0} already exists, could not create it.
ERROR.SettingRolePermissions=Could not set permissions for role {0} during import.
ERROR.ImportingUserSetting=Could not import user settings for user {0}.
